### ISSUE TITLE
Can't uninstall module - notify_responsible

### ISSUE THREAD

**Issue by blessendor** [boolit-team/base-crm-sale#6]
Module not worked for me, odoo 8.
BTW, I can't uninstall with next logged errors:

Odoo Server Error
Traceback (most recent call last):
  File "/opt/openerp/v8/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/openerp/v8/openerp/http.py", line 574, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/openerp/v8/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/openerp/v8/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/openerp/v8/openerp/http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/openerp/v8/openerp/http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "/opt/openerp/v8/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/opt/openerp/v8/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/openerp/v8/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/openerp/v8/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/openerp/v8/openerp/addons/base/module/wizard/base_module_upgrade.py", line 105, in upgrade_module
    openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/opt/openerp/v8/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/openerp/v8/openerp/modules/loading.py", line 423, in load_modules
    registry['ir.module.module'].module_uninstall(cr, SUPERUSER_ID, modules_to_remove.values())
  File "/opt/openerp/v8/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/openerp/v8/openerp/addons/base/module/module.py", line 458, in module_uninstall
    ir_model_data._module_data_uninstall(cr, uid, modules_to_remove, context)
  File "/opt/openerp/v8/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/openerp/v8/openerp/addons/base/ir/ir_model.py", line 1217, in _module_data_uninstall
    ir_model_constraint._module_data_uninstall(cr, uid, constraint_ids, context)
  File "/opt/openerp/v8/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/openerp/v8/openerp/addons/base/ir/ir_model.py", line 575, in _module_data_uninstall
    model_obj = self.pool[model]
  File "/opt/openerp/v8/openerp/modules/registry.py", line 102, in __getitem__
    return self.models[model_name]
KeyError: u'crm.case'

**Comment by blessendor** [comment]
Looks like I can't do anything with any modules with the same error:
KeyError: u'crm.case'

But all I can roll-back in memory - all was OK before I installed 'notify_responsible'.

**Comment by oerp-odoo** [comment]
@blessendor it does not look like it is related with notify_responsible module at all. I could install and uninstall it fine. And it is working as intended. Maybe you don't know what is the purpose of that module? And looking at error it seems you are using some other module that is incorrectly written. It looks for model name `crm.case` which does not exist. And my module does not use such model at all.
